<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;

class TagsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = [
            "salad",
            "hamburger",
            "pizza",
            "pasta",
            "soup",
            "sandwich",
            "steak",
            "chicken",
            "fish",
            "seafood",
            "rice",
            "noodles",
            "tacos",
            "burrito",
            "sushi",
            "curry",
            "stir-fry",
            "casserole",
            "dessert",
            "appetizer",
            "grilled",
            "fried",
            "baked",
            "roasted",
            "steamed",
            "boiled",
            "sautéed",
            "bbq",
            "smoked",
            "raw",
            "pan-fried",
            "deep-fried",
            "air-fried",
            "slow-cooked",
            "pressure-cooked",
            "spicy",
            "mild",
            "sweet",
            "sour",
            "salty",
            "bitter",
            "umami",
            "hot",
            "medium",
            "tangy",
            "savory",
            "bland",
            "flavorful",
            "zesty",
            "rich",
            "vegetarian",
            "vegan",
            "gluten-free",
            "dairy-free",
            "keto",
            "low-carb",
            "high-protein",
            "paleo",
            "mediterranean",
            "organic",
            "sugar-free",
            "low-sodium",
            "whole30",
            "plant-based",
            "kosher",
            "italian",
            "chinese",
            "mexican",
            "indian",
            "thai",
            "japanese",
            "american",
            "french",
            "greek",
            "spanish",
            "korean",
            "vietnamese",
            "turkish",
            "lebanese",
            "brazilian",
            "breakfast",
            "lunch",
            "dinner",
            "snack",
            "brunch",
            "main-course",
            "side-dish",
            "drink",
            "smoothie",
            "juice",
            "crispy",
            "crunchy",
            "soft",
            "creamy",
            "chewy",
            "tender",
            "juicy",
            "dry",
            "moist",
            "smooth",
            "chunky",
            "flaky",
            "sticky",
            "cold",
            "warm",
            "frozen",
            "chilled",
            "room-temperature",
            "healthy",
            "light",
            "heavy",
            "comfort-food",
            "protein-rich",
            "fiber-rich",
            "low-calorie",
            "high-calorie",
            "nutrient-dense",
            "superfood",
            "holiday",
            "party",
            "date-night",
            "family-meal",
            "quick-meal",
            "meal-prep",
            "leftover",
            "takeout",
            "homemade",
            "restaurant-style"
        ];

        Model::unguard();
        foreach ($tags as $index => $tag) {
            Tag::query()->create([
                "id" => $index + 1,
                "name" => $tag,
                "status" => 1,
                'homepage' => 0,
                'priority' => 1000,
            ]);
        }
    }
}
