version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    container_name: mamchef_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "9091:80"
      - "9094:8080"  # Reverb WebSocket port
    volumes:
      - ./:/var/www
      - ./storage/logs:/var/www/storage/logs
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - REDIS_HOST=redis
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080
    networks:
      - laravel
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.6
    container_name: mamchef_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mamchef
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: mamchef
      MYSQL_USER: mamchef
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "9092:3306"
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: mamchef_redis
    restart: unless-stopped
    ports:
      - "9093:6379"
    volumes:
      - redisdata:/data
    networks:
      - laravel

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

networks:
  laravel:
    driver: bridge