<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Addendum Payout - MamChef General Terms</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            line-height: 1.4;
            margin: 20px;
            color: #000;
        }
        h1 {
            font-size: 16px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        h2 {
            font-size: 12px;
            font-weight: bold;
            margin-top: 15px;
            margin-bottom: 10px;
        }
        p {
            margin-bottom: 8px;
            text-align: justify;
        }
        .dynamic-field {
            font-weight: bold;
            background-color: #ffff99;
        }
        .contract-info {
            margin-bottom: 20px;
        }
        .signatures {
            margin-top: 40px;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>ADDENDUM<br>TO THE GENERAL TERMS AND CONDITIONS FOR PARTNERS</h1>

    <div class="contract-info">
        <p><strong>Partner:</strong> <span class="dynamic-field">[{{ $partner_full_name ?? 'Dynamic: Full Name / Company Name, Registration Number, Address' }}]</span></p>

        <p><strong>Platform:</strong> MB "MamChef", a company established under the laws of the Republic of Lithuania, company code 307277177, registered at Krivių g. 5, LT-01204, Vilnius, Republic of Lithuania</p>

        <p><strong>Date of Signature:</strong> <span class="dynamic-field">[Dynamic Date]</span></p>

        <p><strong>Applicable Period:</strong> <span class="dynamic-field">[{{ $applicable_period ?? 'Dynamic Period, e.g., "September 2025"' }}]</span></p>
    </div>

    <p>This Dynamic Addendum ("Addendum") is concluded electronically between the Platform and the Partner identified above (together, the "Parties") and forms an integral part of the GENERAL TERMS AND CONDITIONS FOR PARTNERS ("General Terms"). Unless expressly amended herein, all provisions of the General Terms remain in full force and effect.</p>

    <h2>1. Platform Fee</h2>

    <p>1.1 For the Applicable Period, the Partner shall pay to the Platform the following commissions on net revenue (exclusive of VAT and other applicable taxes) for all eligible Orders completed through the Platform:</p>

    <p>a. <strong>Pickup Orders (no delivery cost):</strong></p>

    <p>– Early Partner Incentive (first 6 months): <span class="dynamic-field">[{{ $early_partner_commission ?? 'Dynamic Commission %' }}]</span>, valid for the first year only.</p>

    <p>– Standard Partners: <span class="dynamic-field">[{{ $standard_commission ?? 'Dynamic Commission %' }}]</span>.</p>

    <p>b. <strong>Partner-Handled Delivery:</strong></p>

    <p>– Fixed Fee: <strong><span class="dynamic-field">[{{ $delivery_fee ?? 'Dynamic Delivery Fee' }}]</span>.</p>

    <h2>2. Service and Marketing Fees</h2>

    <p>2.1 Service Fees shall apply in accordance with the General Terms or as separately agreed in writing.</p>
    <p>2.2 Marketing Fees for promotional campaigns shall only apply where expressly confirmed in writing (including electronic confirmation via the Platform).</p>

    <h2>3. Taxes</h2>

    <p>3.1 All amounts specified in this Addendum are exclusive of VAT and any other applicable taxes.</p>
    <p>3.2 VAT shall be applied at the prevailing statutory rate.</p>

    <h2>4. Settlement and Payout</h2>

    <p>4.1 Payouts to the Partner shall be made in accordance with the General Terms.</p>
    <p>4.2 All deductions (including Platform Fee, Service Fees, Marketing Fees, and taxes) shall be applied prior to payout.</p>
    <p>4.3. Unless agreed otherwise between the Parties, the payouts are performed bi-weekly.</p>

    <h2>5. Dynamic Nature of Addendum</h2>

    <p>5.1 This Addendum has been system-generated by the Platform for the Partner identified above and reflects the payment provisions applicable for the Effective Date and Applicable Period.</p>
    <p>5.2 Upon issuance of a new Addendum, this version shall automatically expire and be replaced by the new Addendum.</p>
    <p>5.3 The Partner acknowledges and accepts that this Addendum is concluded electronically, and that such electronic form shall constitute valid execution and binding agreement for all purposes.</p>
    <p>5.4 By continuing to use the Platform, the Partner confirms acceptance of this Addendum and its incorporation into the General Terms.</p>

    <p>5.5 This Addendum, together with the General Terms, shall be construed and governed in accordance with the laws of the Republic of Lithuania. Any dispute, controversy, or claim arising out of or in connection with this Addendum shall be submitted to the exclusive jurisdiction of the competent courts of Lithuania. The Parties expressly agree that the English language shall be used for this Addendum and the General Terms, and that such use is valid, binding, and acceptable to both Parties.</p>

    <div class="signatures">
        <p><strong>Issued by:</strong> <span class="dynamic-field">[Platform Name / Legal Entity]</span></p>

        <p><strong>Concluded and signed electronically by:</strong> <span class="dynamic-field">[{{ $partner_signature_name ?? 'Dynamic Partner Name / Company Name' }}]</span></p>

        <p><strong>Date:</strong> <span class="dynamic-field">[Dynamic Date]</span></p>
    </div>
</body>
</html>